import onnx
import json
import onnx.numpy_helper as numpy_helper


def get_seperate_weights(model, name):
    [w] = [t for t in model.graph.initializer if t.name == name]
    return numpy_helper.to_array(w).tolist();


if __name__ == '__main__':
    model = onnx.load('../data/inceptionV3.onnx')
    result = {
        "layer1": {
            "way1_w": 0.4580000042915344,
            "way1_b": -0.029999999329447746,
            "way2_w": 0.4480000138282776,
            "way2_b": -0.08799999952316284,
            "way3_w": 0.44999998807907104,
            "way3_b": -0.18799999356269836,
            "c_1_w": get_seperate_weights(model, "926"),
            "c_1_b": get_seperate_weights(model, "927"),
            "c_2_w": get_seperate_weights(model, "929"),
            "c_2_b": get_seperate_weights(model, "930"),
            "c_3_w": get_seperate_weights(model, "932"),
            "c_3_b": get_seperate_weights(model, "933"),
            "c_4_w": get_seperate_weights(model, "935"),
            "c_4_b": get_seperate_weights(model, "936"),
            "c_5_w": get_seperate_weights(model, "938"),
            "c_5_b": get_seperate_weights(model, "939")
        },
        "layer2_1": {
            "way1_w": get_seperate_weights(model, "941"),
            "way1_b": get_seperate_weights(model, "942"),
            "way2_1_w": get_seperate_weights(model, "944"),
            "way2_1_b": get_seperate_weights(model, "945"),
            "way2_2_w": get_seperate_weights(model, "947"),
            "way2_2_b": get_seperate_weights(model, "948"),
            "way3_1_w": get_seperate_weights(model, "950"),
            "way3_1_b": get_seperate_weights(model, "951"),
            "way3_2_w": get_seperate_weights(model, "953"),
            "way3_2_b": get_seperate_weights(model, "954"),
            "way3_3_w": get_seperate_weights(model, "956"),
            "way3_3_b": get_seperate_weights(model, "957"),
            "way4_w": get_seperate_weights(model, "959"),
            "way4_b": get_seperate_weights(model, "960")
        }, 
        "layer2_2": {
            "way1_w": get_seperate_weights(model, "962"),
            "way1_b": get_seperate_weights(model, "963"),
            "way2_1_w": get_seperate_weights(model, "965"),
            "way2_1_b": get_seperate_weights(model, "966"),
            "way2_2_w": get_seperate_weights(model, "968"),
            "way2_2_b": get_seperate_weights(model, "969"),
            "way3_1_w": get_seperate_weights(model, "971"),
            "way3_1_b": get_seperate_weights(model, "972"),
            "way3_2_w": get_seperate_weights(model, "974"),
            "way3_2_b": get_seperate_weights(model, "975"),
            "way3_3_w": get_seperate_weights(model, "977"),
            "way3_3_b": get_seperate_weights(model, "978"),
            "way4_w": get_seperate_weights(model, "980"),
            "way4_b": get_seperate_weights(model, "981")
        },
        "layer2_3": {
            "way1_w": get_seperate_weights(model, "983"),
            "way1_b": get_seperate_weights(model, "984"),
            "way2_1_w": get_seperate_weights(model, "986"),
            "way2_1_b": get_seperate_weights(model, "987"),
            "way2_2_w": get_seperate_weights(model, "989"),
            "way2_2_b": get_seperate_weights(model, "990"),
            "way3_1_w": get_seperate_weights(model, "992"),
            "way3_1_b": get_seperate_weights(model, "993"),
            "way3_2_w": get_seperate_weights(model, "995"),
            "way3_2_b": get_seperate_weights(model, "996"),
            "way3_3_w": get_seperate_weights(model, "998"),
            "way3_3_b": get_seperate_weights(model, "999"),
            "way4_w": get_seperate_weights(model, "1001"),
            "way4_b": get_seperate_weights(model, "1002")
        },        
        "layer3": {
            "way1_w": get_seperate_weights(model, "1004"),
            "way1_b": get_seperate_weights(model, "1005"),
            "way2_1_w": get_seperate_weights(model, "1007"),
            "way2_1_b": get_seperate_weights(model, "1008"),
            "way2_2_w": get_seperate_weights(model, "1010"),
            "way2_2_b": get_seperate_weights(model, "1011"),
            "way2_3_w": get_seperate_weights(model, "1013"),
            "way2_3_b": get_seperate_weights(model, "1014")
        },
        "layer4_1": {
            "way1_w": get_seperate_weights(model, "1016"),
            "way1_b": get_seperate_weights(model, "1017"),
            "way2_1_w": get_seperate_weights(model, "1019"),
            "way2_1_b": get_seperate_weights(model, "1020"),
            "way2_2_w": get_seperate_weights(model, "1022"),
            "way2_2_b": get_seperate_weights(model, "1023"),
            "way2_3_w": get_seperate_weights(model, "1025"),
            "way2_3_b": get_seperate_weights(model, "1026"),
            "way3_1_w": get_seperate_weights(model, "1028"),
            "way3_1_b": get_seperate_weights(model, "1029"),
            "way3_2_w": get_seperate_weights(model, "1031"),
            "way3_2_b": get_seperate_weights(model, "1032"),
            "way3_3_w": get_seperate_weights(model, "1034"),
            "way3_3_b": get_seperate_weights(model, "1035"),
            "way3_4_w": get_seperate_weights(model, "1037"),
            "way3_4_b": get_seperate_weights(model, "1038"),
            "way3_5_w": get_seperate_weights(model, "1040"),
            "way3_5_b": get_seperate_weights(model, "1041"),
            "way4_w": get_seperate_weights(model, "1043"),
            "way4_b": get_seperate_weights(model, "1044")
        },
        "layer4_2": {
            "way1_w": get_seperate_weights(model, "1046"),
            "way1_b": get_seperate_weights(model, "1047"),
            "way2_1_w": get_seperate_weights(model, "1049"),
            "way2_1_b": get_seperate_weights(model, "1050"),
            "way2_2_w": get_seperate_weights(model, "1052"),
            "way2_2_b": get_seperate_weights(model, "1053"),
            "way2_3_w": get_seperate_weights(model, "1055"),
            "way2_3_b": get_seperate_weights(model, "1056"),
            "way3_1_w": get_seperate_weights(model, "1058"),
            "way3_1_b": get_seperate_weights(model, "1059"),
            "way3_2_w": get_seperate_weights(model, "1061"),
            "way3_2_b": get_seperate_weights(model, "1062"),
            "way3_3_w": get_seperate_weights(model, "1064"),
            "way3_3_b": get_seperate_weights(model, "1065"),
            "way3_4_w": get_seperate_weights(model, "1067"),
            "way3_4_b": get_seperate_weights(model, "1068"),
            "way3_5_w": get_seperate_weights(model, "1070"),
            "way3_5_b": get_seperate_weights(model, "1071"),
            "way4_w": get_seperate_weights(model, "1073"),
            "way4_b": get_seperate_weights(model, "1074")
        },
        "layer4_3": {
            "way1_w": get_seperate_weights(model, "1076"),
            "way1_b": get_seperate_weights(model, "1077"),
            "way2_1_w": get_seperate_weights(model, "1079"),
            "way2_1_b": get_seperate_weights(model, "1080"),
            "way2_2_w": get_seperate_weights(model, "1082"),
            "way2_2_b": get_seperate_weights(model, "1083"),
            "way2_3_w": get_seperate_weights(model, "1085"),
            "way2_3_b": get_seperate_weights(model, "1086"),
            "way3_1_w": get_seperate_weights(model, "1088"),
            "way3_1_b": get_seperate_weights(model, "1089"),
            "way3_2_w": get_seperate_weights(model, "1091"),
            "way3_2_b": get_seperate_weights(model, "1092"),
            "way3_3_w": get_seperate_weights(model, "1094"),
            "way3_3_b": get_seperate_weights(model, "1095"),
            "way3_4_w": get_seperate_weights(model, "1097"),
            "way3_4_b": get_seperate_weights(model, "1098"),
            "way3_5_w": get_seperate_weights(model, "1100"),
            "way3_5_b": get_seperate_weights(model, "1101"),
            "way4_w": get_seperate_weights(model, "1103"),
            "way4_b": get_seperate_weights(model, "1104")
        },
        "layer4_4": {
            "way1_w": get_seperate_weights(model, "1106"),
            "way1_b": get_seperate_weights(model, "1107"),
            "way2_1_w": get_seperate_weights(model, "1109"),
            "way2_1_b": get_seperate_weights(model, "1110"),
            "way2_2_w": get_seperate_weights(model, "1112"),
            "way2_2_b": get_seperate_weights(model, "1113"),
            "way2_3_w": get_seperate_weights(model, "1115"),
            "way2_3_b": get_seperate_weights(model, "1116"),
            "way3_1_w": get_seperate_weights(model, "1118"),
            "way3_1_b": get_seperate_weights(model, "1119"),
            "way3_2_w": get_seperate_weights(model, "1121"),
            "way3_2_b": get_seperate_weights(model, "1122"),
            "way3_3_w": get_seperate_weights(model, "1124"),
            "way3_3_b": get_seperate_weights(model, "1125"),
            "way3_4_w": get_seperate_weights(model, "1127"),
            "way3_4_b": get_seperate_weights(model, "1128"),
            "way3_5_w": get_seperate_weights(model, "1130"),
            "way3_5_b": get_seperate_weights(model, "1131"),
            "way4_w": get_seperate_weights(model, "1133"),
            "way4_b": get_seperate_weights(model, "1134")
        },
        "layer5": {
            "way1_1_w": get_seperate_weights(model, "1136"),
            "way1_1_b": get_seperate_weights(model, "1137"),
            "way1_2_w": get_seperate_weights(model, "1139"),
            "way1_2_b": get_seperate_weights(model, "1140"),
            "way2_1_w": get_seperate_weights(model, "1142"),
            "way2_1_b": get_seperate_weights(model, "1143"),
            "way2_2_w": get_seperate_weights(model, "1145"),
            "way2_2_b": get_seperate_weights(model, "1146"),
            "way2_3_w": get_seperate_weights(model, "1148"),
            "way2_3_b": get_seperate_weights(model, "1149"),
            "way2_4_w": get_seperate_weights(model, "1151"),
            "way2_4_b": get_seperate_weights(model, "1152")
        },
        "layer6_1": {
            "way1_w": get_seperate_weights(model, "1154"),
            "way1_b": get_seperate_weights(model, "1155"),
            "way23_1_w": get_seperate_weights(model, "1157"),
            "way23_1_b": get_seperate_weights(model, "1158"),
            "way2_2_w": get_seperate_weights(model, "1160"),
            "way2_2_b": get_seperate_weights(model, "1161"),
            "way3_2_w": get_seperate_weights(model, "1163"),
            "way3_2_b": get_seperate_weights(model, "1164"),
            "way45_1_w": get_seperate_weights(model, "1166"),
            "way45_1_b": get_seperate_weights(model, "1167"),
            "way45_2_w": get_seperate_weights(model, "1169"),
            "way45_2_b": get_seperate_weights(model, "1170"),
            "way4_3_w": get_seperate_weights(model, "1172"),
            "way4_3_b": get_seperate_weights(model, "1173"),
            "way5_3_w": get_seperate_weights(model, "1175"),
            "way5_3_b": get_seperate_weights(model, "1176"),
            "way6_w": get_seperate_weights(model, "1178"),
            "way6_b": get_seperate_weights(model, "1179")
        },
        "layer6_2": {
            "way1_w": get_seperate_weights(model, "1181"),
            "way1_b": get_seperate_weights(model, "1182"),
            "way23_1_w": get_seperate_weights(model, "1184"),
            "way23_1_b": get_seperate_weights(model, "1185"),
            "way2_2_w": get_seperate_weights(model, "1187"),
            "way2_2_b": get_seperate_weights(model, "1188"),
            "way3_2_w": get_seperate_weights(model, "1190"),
            "way3_2_b": get_seperate_weights(model, "1191"),
            "way45_1_w": get_seperate_weights(model, "1193"),
            "way45_1_b": get_seperate_weights(model, "1194"),
            "way45_2_w": get_seperate_weights(model, "1196"),
            "way45_2_b": get_seperate_weights(model, "1197"),
            "way4_3_w": get_seperate_weights(model, "1199"),
            "way4_3_b": get_seperate_weights(model, "1200"),
            "way5_3_w": get_seperate_weights(model, "1202"),
            "way5_3_b": get_seperate_weights(model, "1203"),
            "way6_w": get_seperate_weights(model, "1205"),
            "way6_b": get_seperate_weights(model, "1206")
        },
        "outputlayer": {
            "fc_w": get_seperate_weights(model, "fc.weight"),
            "fc_b": get_seperate_weights(model, "fc.bias")
        }
    }
    with open('../data/inceptionV3.json', 'w') as fp:
        json.dump(result, fp)